### ISSUE TITLE
[Bug] Connect wallet with different permissions

### ISSUE THREAD

**Issue by zh-kai** [demox-labs/aleo-wallet-adapter#11]
Hi team.

If I change the connection permissions for my *dapp*, do I have to unlock the previous permissions in *Leo Wallet*?

Is it possible to change connection permissions and then override the previous permissions?

**Comment by evanmarshall** [comment]
Right now it's only possible if the user removes the DApp permission in their wallet and then re-connects to the DApp with a different permission.

<img width="710" alt="Screenshot 2023-09-27 at 5 08 08 PM" src="https://github.com/demox-labs/aleo-wallet-adapter/assets/1102811/dc1b0406-b9c1-4fc9-862d-668fb20559c8">

**Comment by evanmarshall** [comment]
I should update that the request flow is now that a DApp calls `disconnect` and then `connect` with the new permission
