### ISSUE TITLE
About `transactionId`

### ISSUE THREAD

**Issue by zh-kai** [demox-labs/aleo-wallet-adapter#7]
Hello team,

I was wondering if there is a way to calculate the `Aleo Transaction ID` from the `transactionId` returned by the `requestTransaction` method.

Thank you and best regards.

**Comment by evanmarshall** [comment]
Currently there is not. The `transactionId` is a uuid generated within a wallet and is meant to preserve privacy for the transaction. Could you help describe your use & I'd be happy to suggest a usage pattern for the adapter.

**Comment by zh-kai** [comment]
> Currently there is not. The `transactionId` is a uuid generated within a wallet and is meant to preserve privacy for the transaction. Could you help describe your use & I'd be happy to suggest a usage pattern for the adapter.

I want to make a Dapp that interacts with Leo Wallet & provides transaction history for users, allowing them to easily view the details on [Haruka's Aleo Explorer](https://explorer.hamp.app/).

Thank you for your help! 😄

**Comment by evanmarshall** [comment]
It makes a lot of sense but we have to consider the privacy implications. I'm thinking we can add another DAppPermission type to enable sharing history. You would then be able to request transactions initiated by and records owned by the user. Would that be sufficient or do you imagine a different implementation?

**Comment by zh-kai** [comment]
That's enough for me, thanks for your help!

**Comment by zh-kai** [comment]
Any update?

**Comment by evanmarshall** [comment]
This is in progress right now. It should be available within a week

**Comment by evanmarshall** [comment]
The adapter is now updated and supported in version 0.0.26 of the Leo Wallet. https://github.com/demox-labs/aleo-wallet-adapter#%EF%B8%8Frequesting-record-plaintexts

0.0.26 has been submitted to the chrome store and should be available within 12 hours.

It will require using the OnChainHistory permission in your application.

**Comment by zh-kai** [comment]
> 

thanks for your help!
