### ISSUE TITLE
[Bug] Record for transaction input may be the same as fee

### ISSUE THREAD

**Issue by elderhammer** [demox-labs/aleo-wallet-adapter#9]
## 🐛 Bug Report

Record for transaction input may be the same as fee,
and the execution will be fail: "Something went wrong: Found duplicate input IDs in the transaction"
![20230713095524](https://github.com/demox-labs/aleo-wallet-adapter/assets/81279860/0cb02e87-45b6-4279-b226-bb269b5f7ab8)

## Steps to Reproduce

1. You have more than one credit record on your aleo account
2. Visit: https://demo.leo.app/execute
3. Submit a transfer, then copy the fee record in the pop-up window, and finally reject to confirmation
4. Submit the transfer again using the copied record as input, you will find that the input is the same as the fee

## Expected Behavior

Fee record will be selected from a record that is not an input.

## Your Environment

- Promgram: credits.aleo
- Leo Wallet Version: 0.0.21

**Comment by evanmarshall** [comment]
This is in progress and should be fixed within a week

**Comment by evanmarshall** [comment]
This was a bug in the wallet and has been fixed on the previous release.
